# Generated by Django 5.0.7 on 2024-08-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coins",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=255,
                null=True,
                verbose_name="Монеты",
            ),
        ),
    ]
